### PR TITLE
make py32 and pypy3 CI compatible and  add extra python version tested

### PR DESCRIPTION
**Pull request by yupbank**
added py35, py36

### CODE REVIEW

**Comment by SylvainDe** [comment]
Thank you very much! I'll have a look at this asap (I don't know much about this so I'll have to dive into the documentation first).

**Comment by pmangg** [comment]
cc @SimonSapin what do you think about this?

**Comment by SimonSapin** [comment]
I don’t really have an opinion. I defer to @liZe.

**Comment by liZe** [comment]
Thanks for your help.

I've had bad moments with tox, and I'd prefer to rely on Travis and `setup.py` to launch tests, just as it's done in [Radicale](https://github.com/Kozea/Radicale/blob/master/.travis.yml) or [WeasyPrint](https://github.com/Kozea/WeasyPrint/blob/master/.travis.yml). This way, we could also launch tests on MacOS too.

**Pull request closed without merging**
